-- DROP DATABASE trialmaple_db;
-- CREATE DATABASE trialmaple_db;

INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Final Enigma",350,"INHUMANE",8,162980440,1,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Acramaxo",330,"INHUMANE",1,1316620,1,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Uncanny Valley",270,"INHUMANE",6,5119230,5,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Black Cyalume: Neon Chrome",260,"INHUMANE",10,29639980,3,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("The possible 7",250,"INHUMANE",7,12135040,2,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Carton Hop",250,"INHUMANE",2,6191960,3,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("The Twisted Treeline",210,"INHUMANE",0,2686200,1,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Caffeine",210,"INHUMANE",3,7480460,4,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Black Cyalume: Afterglow",150,"INHUMANE",10,4230200,8,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Forgotten Dynasty",145,"INHUMANE",15,9673840,6,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Sol",140,"INHUMANE",6,3970730,5,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Something on ACID",135,"INHUMANE",9,4200540,12,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("zurg",120,"INHUMANE",4,1802410,11,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Decay",105,"INHUMANE",13,3999380,11,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Black Cyalume",105,"INHUMANE",10,2725250,23,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Delta-v",100,"INHUMANE",5,641110,20,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Choreography",90,"EXTREME",16,6229990,16,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Calmth",90,"EXTREME",9,5735350,16,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Tartarus",85,"EXTREME",9,2026030,25,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Mahârâja",85,"EXTREME",16,7520470,14,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("T.A.L.O.S",80,"EXTREME",20,4699650,20,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Disintegration",80,"EXTREME",222,27466070,12,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("TRON",70,"EXTREME",17,7020490,21,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("tree house",70,"EXTREME",6,1544090,16,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Decimation",70,"EXTREME",188,12813290,22,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Terraform",65,"EXTREME",11,2501380,11,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Arena Eternal",60,"EXTREME",25,1214700,27,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Under Construction...",55,"EXTREME",5,1228120,10,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Spandrelism",55,"EXTREME",19,767810,29,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Midas",55,"EXTREME",7,733450,27,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("trial_map.Gbx",50,"EXTREME",20,1710030,12,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("/½/¾/",50,"EXTREME",11,2261040,20,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("The Hadean",45,"HARDCORE",11,2900870,28,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Shangri La",45,"HARDCORE",20,3231630,28,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("o f f w o r l d",45,"HARDCORE",6,489750,21,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Hyperdrive",45,"HARDCORE",6,1015260,21,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Gates of Hades",45,"HARDCORE",0,86370,30,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Sign Language",40,"HARDCORE",14,2713740,25,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Shining Sands",40,"HARDCORE",43,4516670,21,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Project YoRHa",40,"HARDCORE",37,5993110,30,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Pipeline",40,"HARDCORE",101,9055250,49,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Intergalactic",40,"HARDCORE",88,6528400,38,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("FROSTPUNK",40,"HARDCORE",16,3355590,25,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Cretaceous Period",40,"HARDCORE",20,2439990,35,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Another Pipe Challenge for Gamers",40,"HARDCORE",20,3335720,13,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Sandtrap",35,"HARDCORE",10,873460,41,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Radiation",35,"HARDCORE",111,9852000,33,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Quandary",35,"HARDCORE",17,2794370,35,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Psychosomatic Exhaustion",35,"HARDCORE",22,2731460,34,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Pipe Challenge for Gamers",35,"HARDCORE",35,3565280,26,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Chocobo Jam",35,"HARDCORE",12,1349700,37,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Branching Path",35,"HARDCORE",66,4271220,30,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Agglomeration",35,"HARDCORE",15,2652330,37,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Rainbow Tylenol 3",30,"HARDCORE",10,1769310,38,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Rainbow Tylenol",30,"HARDCORE",22,1379980,51,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Oriental Sanctuary",30,"HARDCORE",14,926850,44,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("New 'n Tasty",30,"HARDCORE",28,1844700,47,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("MONKETRIAL",30,"HARDCORE",12,506540,35,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Lost in the Forest",30,"HARDCORE",27,1902720,40,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Haywire",30,"HARDCORE",1,219920,15,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Enantiomorph",30,"HARDCORE",26,3269920,20,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Crimson Realm",30,"HARDCORE",17,2727960,43,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("C e l e s t i a l .",30,"HARDCORE",18,1234040,45,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Azure Citadel",30,"HARDCORE",13,818580,33,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Augmented Past",30,"HARDCORE",15,2942600,35,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Oachkatzlschwoafs on ICE",25,"EXPERT",18,968170,69,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("liminal",25,"EXPERT",19,1939880,28,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("K a n n a g a r i",25,"EXPERT",11,2375350,37,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Jammed Up",25,"EXPERT",9,1909750,35,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Deadlock",25,"EXPERT",18,1627530,44,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Chaos Emeralds",25,"EXPERT",20,1850170,46,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Aspiration",25,"EXPERT",30,2049450,39,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Agglutinate",25,"EXPERT",16,2549850,34,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Vacuous",20,"EXPERT",14,1524330,47,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Vacation.",20,"EXPERT",18,1220200,61,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("The Journey",20,"EXPERT",44,2610230,52,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Tenebris",20,"EXPERT",15,1893040,38,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Suduaya",20,"EXPERT",14,894550,47,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Narehate",20,"EXPERT",23,1828430,31,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("MilkyHighWay",20,"EXPERT",18,1169940,65,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Marsella Miradors",20,"EXPERT",23,2848390,57,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("magnetic distortions.",20,"EXPERT",20,452420,69,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Ligneous Megalopolitan",20,"EXPERT",12,1601740,51,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Gehenna",20,"EXPERT",17,2426560,39,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Aggregate",20,"EXPERT",17,2376430,50,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Aggiornamento",20,"EXPERT",17,676510,33,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Woolen Calamity",15,"EXPERT",16,1249860,79,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Uaxactun",15,"EXPERT",16,717850,133,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Spirit's glade",15,"EXPERT",14,837960,63,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Silversong",15,"EXPERT",13,987060,62,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Reign of Kronos",15,"EXPERT",20,976110,116,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Rainbow Tylenol 2",15,"EXPERT",11,1200740,78,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Psychosomatic Exhaustion 2",15,"EXPERT",43,2172180,97,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("PEZ",15,"EXPERT",13,1068110,108,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("octahedral",15,"EXPERT",15,1115160,73,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Krakatindur",15,"EXPERT",11,847880,116,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Feria Sevilla.",15,"EXPERT",11,520990,73,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Endless Sunrise",15,"EXPERT",17,815670,62,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Empyreum",15,"EXPERT",8,731770,53,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Cryptomnesia",15,"EXPERT",15,894750,58,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Ashbreaker",15,"EXPERT",17,1103140,46,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("ASEC",15,"EXPERT",16,1557160,64,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Ancient Myth",15,"EXPERT",9,2753570,20,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Aggrandizement",15,"EXPERT",22,1271990,89,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("aerial toms",15,"EXPERT",17,1344400,66,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Super Monkey Ball",10,"CHALLENGING",20,1010310,69,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Shadowed Reflections",10,"CHALLENGING",27,1769140,51,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Ringworld",10,"CHALLENGING",30,602820,71,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Restriction",10,"CHALLENGING",15,694240,48,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Relikt",10,"CHALLENGING",21,1288700,60,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Pipe Torture",10,"CHALLENGING",15,768480,87,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Phantom Realm",10,"CHALLENGING",14,608090,95,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Oriental Reverie",10,"CHALLENGING",18,539200,102,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Oneiros",10,"CHALLENGING",20,1123200,78,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Nando Industries",10,"CHALLENGING",7,184220,83,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Lumaria",10,"CHALLENGING",29,1013750,101,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Last Chapter",10,"CHALLENGING",15,937980,86,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("I.O.N.",10,"CHALLENGING",11,484840,43,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Infernal Gauntlet",10,"CHALLENGING",19,894610,93,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Khepri Ur",10,"CHALLENGING",10,817130,90,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Hidden Palace",10,"CHALLENGING",11,853520,88,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Heaven's on FIRE",10,"CHALLENGING",61,2739210,77,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Groundhog Asylum",10,"CHALLENGING",15,650460,67,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Field of currents",10,"CHALLENGING",8,106025,13,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Farewell Quest",10,"CHALLENGING",12,809680,53,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Dune",10,"CHALLENGING",20,799980,59,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Curse of the Ancients",10,"CHALLENGING",20,388430,110,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Crocodile Dundee",10,"CHALLENGING",10,175060,95,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("croaking toad",10,"CHALLENGING",6,274250,115,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("complexity of road works",10,"CHALLENGING",35,1649080,92,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Badlands",10,"CHALLENGING",69,2786640,102,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Auburn Estuary",10,"CHALLENGING",16,963870,90,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Ascension to Heaven",10,"CHALLENGING",12,775950,92,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Arcadia",10,"CHALLENGING",22,770140,52,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Abstracture",10,"CHALLENGING",20,1020220,109,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Threadbare",10,"CHALLENGING",17,1245700,31,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Roofs of Dubai",5,"CHALLENGING",31,1185360,145,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Respiration",5,"CHALLENGING",23,859150,119,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Nyxorithal",5,"CHALLENGING",20,726780,138,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Natrialum",5,"CHALLENGING",34,882190,280,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Metavoid",5,"CHALLENGING",19,699900,157,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Metallic Solstice",5,"CHALLENGING",18,688650,106,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Lavender Town",5,"CHALLENGING",21,526720,296,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Hydrogen",5,"CHALLENGING",20,409990,309,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Hidden Curiosity",5,"CHALLENGING",21,891700,160,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Glorpium",5,"CHALLENGING",38,1414860,82,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Fury Road",5,"CHALLENGING",32,1469030,150,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Eternal Winter",5,"CHALLENGING",11,407060,147,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Elysium",5,"CHALLENGING",10,340520,177,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Cygnus",5,"CHALLENGING",14,453980,137,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Cloudburst.",5,"CHALLENGING",37,992630,120,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Cloud District",5,"CHALLENGING",26,644980,217,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("City of Tears",5,"CHALLENGING",15,439410,184,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("carbon universe.",5,"CHALLENGING",31,938720,111,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Canopus",5,"CHALLENGING",13,389650,175,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("A S T R A L",5,"CHALLENGING",21,593140,231,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Abe's Oddysee",5,"CHALLENGING",17,879680,146,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Erebus",0,"NAMELESS",3,NULL,0,1);
INSERT INTO trial_map(name, points, difficulty, checkpoint_count, world_record, finisher_count, active) VALUES ("Dystopia",0,"NAMELESS",3,NULL,0,1);

INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Final Enigma"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Acramaxo"), "Vonix");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Uncanny Valley"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Black Cyalume: Neon Chrome"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="The possible 7"), "Wasker");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Carton Hop"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="The Twisted Treeline"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Caffeine"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Black Cyalume: Afterglow"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Forgotten Dynasty"), "Muffles");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Sol"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Something on ACID"), "igntuL");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="zurg"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Decay"), "flex");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Black Cyalume"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Delta-v"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Choreography"), "Skyline");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Calmth"), "Konde");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Tartarus"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Mahârâja"), "Nunni");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="T.A.L.O.S"), "Muffles");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Disintegration"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Disintegration"), "loe");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Disintegration"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="TRON"), "Skyline");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="tree house"), "flex");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Decimation"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Decimation"), "loe");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Decimation"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Terraform"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Arena Eternal"), "Muffles");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Under Construction..."), "vcou");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Spandrelism"), "Paxiuz");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Midas"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="trial_map.Gbx"), "rawa");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="/½/¾/"), "Viiru");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="The Hadean"), "Konde");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Shangri La"), "malun22");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="o f f w o r l d"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Hyperdrive"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Gates of Hades"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Sign Language"), "Vonix");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Shining Sands"), "Michu");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Project YoRHa"), "Michu");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Pipeline"), "loe");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Intergalactic"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="FROSTPUNK"), "rawa");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Cretaceous Period"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Another Pipe Challenge for Gamers"), "Jere");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Sandtrap"), "andi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Radiation"), "Fabi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Quandary"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Psychosomatic Exhaustion"), "Wasker");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Pipe Challenge for Gamers"), "Jere");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Chocobo Jam"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Branching Path"), "Ryba");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Agglomeration"), "Vadi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Rainbow Tylenol 3"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Rainbow Tylenol"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Oriental Sanctuary"), "Muffles");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="New 'n Tasty"), "Ryba");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="New 'n Tasty"), "Muffles");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="MONKETRIAL"), "Monkeys");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Lost in the Forest"), "Reahx");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Lost in the Forest"), "Xenn");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Haywire"), "loe, nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Enantiomorph"), "Michu");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Crimson Realm"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Crimson Realm"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="C e l e s t i a l ."), "Michu");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="C e l e s t i a l ."), "Muffles");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Azure Citadel"), "SuperKulPerson");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Augmented Past"), "Bubble");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Oachkatzlschwoafs on ICE"), "igntuL");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="liminal"), "Viiru");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="K a n n a g a r i"), "Michu");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Jammed Up"), "Wasker");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Deadlock"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Deadlock"), "Manu");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Chaos Emeralds"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Aspiration"), "Golden");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Agglutinate"), "Vadi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Vacuous"), "Konde");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Vacation."), "Ryba");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="The Journey"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Tenebris"), "iklu");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Suduaya"), "loe");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Suduaya"), "Bubble");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Narehate"), "Michu");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="MilkyHighWay"), "Muffles");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Marsella Miradors"), "KristOff13");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="magnetic distortions."), "Xenn");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="magnetic distortions."), "Thom");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Ligneous Megalopolitan"), "Sokko");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Gehenna"), "Vonix");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Aggregate"), "Vadi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Aggiornamento"), "Vadi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Woolen Calamity"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Uaxactun"), "Manu");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Spirit's glade"), "Michu");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Silversong"), "Muffles");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Silversong"), "facecat");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Reign of Kronos"), "Muffles");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Rainbow Tylenol 2"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Psychosomatic Exhaustion 2"), "Wasker");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="PEZ"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="octahedral"), "niati");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Krakatindur"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Feria Sevilla."), "Xenn");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Feria Sevilla."), "Agent");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Endless Sunrise"), "Slater");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Empyreum"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Cryptomnesia"), "tnec");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Ashbreaker"), "Slater");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Ashbreaker"), "facecat");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="ASEC"), "Skyline");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="ASEC"), "Vonix");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Ancient Myth"), "Fabi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Aggrandizement"), "Vadi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="aerial toms"), "andi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Super Monkey Ball"), "Eron");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Shadowed Reflections"), "Fabi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Ringworld"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Restriction"), "Ryba");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Relikt"), "Vonix");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Pipe Torture"), "RazoR");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Phantom Realm"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Oriental Reverie"), "Michu");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Oriental Reverie"), "Muffles");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Oneiros"), "Vonix");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Nando Industries"), "Slater");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Lumaria"), "andi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Lumaria"), "loe");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Last Chapter"), "Techno");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="I.O.N."), "Fabi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Infernal Gauntlet"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Khepri Ur"), "facecat");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Khepri Ur"), "CamoBrie");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Hidden Palace"), "KristOff13");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Heaven's on FIRE"), "IgntuL");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Heaven's on FIRE"), "eie");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Groundhog Asylum"), "Falcon");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Field of currents"), "Konde");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Farewell Quest"), "Funnyoscar");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Dune"), "Golden");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Curse of the Ancients"), "Muffles");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Crocodile Dundee"), "igntuL");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="croaking toad"), "nixion");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="complexity of road works"), "deus");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Badlands"), "Muffles");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Auburn Estuary"), "loe");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Ascension to Heaven"), "Eron");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Arcadia"), "SuperKulPerson");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Arcadia"), "niati");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Abstracture"), "Vonix");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Threadbare"), "Konde");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Roofs of Dubai"), "Reahx");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Roofs of Dubai"), "Maurice");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Respiration"), "Golden");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Nyxorithal"), "Fabi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Natrialum"), "loe");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Metavoid"), "loe");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Metavoid"), "andi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Metallic Solstice"), "Eron");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Lavender Town"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Lavender Town"), "igntuL");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Hydrogen"), "igntuL");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Hidden Curiosity"), "Fabi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Glorpium"), "Fabi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Fury Road"), "adi_mot");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Eternal Winter"), "Michu");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Elysium"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Cygnus"), "Wasker");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Cloudburst."), "Fabi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Cloud District"), "Muffles");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="City of Tears"), "andi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="carbon universe."), "Fabi");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Canopus"), "Techno");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="A S T R A L"), "thom");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Abe's Oddysee"), "adi_mot");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Erebus"), "simo_900");
INSERT INTO trial_map_authors(trial_map_id, author) VALUES ((SELECT id FROM trial_map WHERE name="Dystopia"), "Flex");
