ALTER TABLE trial_map ADD COLUMN release_year INT(11) DEFAULT NULL;
UPDATE trial_map SET release_year=2017 WHERE name="Final Enigma";
UPDATE trial_map SET release_year=2021 WHERE name="Acramaxo";
UPDATE trial_map SET release_year=2018 WHERE name="Uncanny Valley";
UPDATE trial_map SET release_year=2025 WHERE name="Black Cyalume: Neon Chrome";
UPDATE trial_map SET release_year=2018 WHERE name="The possible 7";
UPDATE trial_map SET release_year=2021 WHERE name="Carton Hop";
UPDATE trial_map SET release_year=2021 WHERE name="The Twisted Treeline";
UPDATE trial_map SET release_year=2021 WHERE name="Caffeine";
UPDATE trial_map SET release_year=2020 WHERE name="Black Cyalume: Afterglow";
UPDATE trial_map SET release_year=2025 WHERE name="Forgotten Dynasty";
UPDATE trial_map SET release_year=2021 WHERE name="Sol";
UPDATE trial_map SET release_year=2016 WHERE name="Something on ACID";
UPDATE trial_map SET release_year=2019 WHERE name="zurg";
UPDATE trial_map SET release_year=2022 WHERE name="Decay";
UPDATE trial_map SET release_year=2015 WHERE name="Black Cyalume";
UPDATE trial_map SET release_year=2019 WHERE name="Delta-v";
UPDATE trial_map SET release_year=2023 WHERE name="Choreography";
UPDATE trial_map SET release_year=2020 WHERE name="Calmth";
UPDATE trial_map SET release_year=2021 WHERE name="Tartarus";
UPDATE trial_map SET release_year=2017 WHERE name="Mahârâja";
UPDATE trial_map SET release_year=2021 WHERE name="T.A.L.O.S";
UPDATE trial_map SET release_year=2023 WHERE name="Disintegration";
UPDATE trial_map SET release_year=2021 WHERE name="TRON";
UPDATE trial_map SET release_year=2022 WHERE name="tree house";
UPDATE trial_map SET release_year=2019 WHERE name="Decimation";
UPDATE trial_map SET release_year=2025 WHERE name="Terraform";
UPDATE trial_map SET release_year=2022 WHERE name="Arena Eternal";
UPDATE trial_map SET release_year=2024 WHERE name="Under Construction...";
UPDATE trial_map SET release_year=2023 WHERE name="Spandrelism";
UPDATE trial_map SET release_year=2020 WHERE name="Midas";
UPDATE trial_map SET release_year=2025 WHERE name="trial_map.Gbx";
UPDATE trial_map SET release_year=2024 WHERE name="/½/¾/";
UPDATE trial_map SET release_year=2016 WHERE name="The Hadean";
UPDATE trial_map SET release_year=2018 WHERE name="Shangri La";
UPDATE trial_map SET release_year=2025 WHERE name="o f f w o r l d";
UPDATE trial_map SET release_year=2023 WHERE name="Hyperdrive";
UPDATE trial_map SET release_year=2019 WHERE name="Gates of Hades";
UPDATE trial_map SET release_year=2022 WHERE name="Sign Language";
UPDATE trial_map SET release_year=2023 WHERE name="Shining Sands";
UPDATE trial_map SET release_year=2022 WHERE name="Project YoRHa";
UPDATE trial_map SET release_year=2020 WHERE name="Pipeline";
UPDATE trial_map SET release_year=2014 WHERE name="Intergalactic";
UPDATE trial_map SET release_year=2022 WHERE name="FROSTPUNK";
UPDATE trial_map SET release_year=2015 WHERE name="Cretaceous Period";
UPDATE trial_map SET release_year=2025 WHERE name="Another Pipe Challenge for Gamers";
UPDATE trial_map SET release_year=2023 WHERE name="Sandtrap";
UPDATE trial_map SET release_year=2024 WHERE name="Radiation";
UPDATE trial_map SET release_year=2016 WHERE name="Quandary";
UPDATE trial_map SET release_year=2018 WHERE name="Psychosomatic Exhaustion";
UPDATE trial_map SET release_year=2024 WHERE name="Pipe Challenge for Gamers";
UPDATE trial_map SET release_year=2018 WHERE name="Chocobo Jam";
UPDATE trial_map SET release_year=2023 WHERE name="Branching Path";
UPDATE trial_map SET release_year=2021 WHERE name="Agglomeration";
UPDATE trial_map SET release_year=2019 WHERE name="Rainbow Tylenol 3";
UPDATE trial_map SET release_year=2014 WHERE name="Rainbow Tylenol";
UPDATE trial_map SET release_year=2021 WHERE name="Oriental Sanctuary";
UPDATE trial_map SET release_year=2022 WHERE name="New 'n Tasty";
UPDATE trial_map SET release_year=2023 WHERE name="MONKETRIAL";
UPDATE trial_map SET release_year=2015 WHERE name="Lost in the Forest";
UPDATE trial_map SET release_year=2025 WHERE name="Haywire";
UPDATE trial_map SET release_year=2024 WHERE name="Enantiomorph";
UPDATE trial_map SET release_year=2018 WHERE name="Crimson Realm";
UPDATE trial_map SET release_year=2020 WHERE name="C e l e s t i a l .";
UPDATE trial_map SET release_year=2023 WHERE name="Azure Citadel";
UPDATE trial_map SET release_year=2016 WHERE name="Augmented Past";
UPDATE trial_map SET release_year=2011 WHERE name="Oachkatzlschwoafs on ICE";
UPDATE trial_map SET release_year=2025 WHERE name="liminal";
UPDATE trial_map SET release_year=2021 WHERE name="K a n n a g a r i";
UPDATE trial_map SET release_year=2018 WHERE name="Jammed Up";
UPDATE trial_map SET release_year=2016 WHERE name="Deadlock";
UPDATE trial_map SET release_year=2021 WHERE name="Chaos Emeralds";
UPDATE trial_map SET release_year=2024 WHERE name="Aspiration";
UPDATE trial_map SET release_year=2022 WHERE name="Agglutinate";
UPDATE trial_map SET release_year=2022 WHERE name="Vacuous";
UPDATE trial_map SET release_year=2022 WHERE name="Vacation.";
UPDATE trial_map SET release_year=2019 WHERE name="The Journey";
UPDATE trial_map SET release_year=2023 WHERE name="Tenebris";
UPDATE trial_map SET release_year=2017 WHERE name="Suduaya";
UPDATE trial_map SET release_year=2024 WHERE name="Narehate";
UPDATE trial_map SET release_year=2020 WHERE name="MilkyHighWay";
UPDATE trial_map SET release_year=2022 WHERE name="Marsella Miradors";
UPDATE trial_map SET release_year=2017 WHERE name="magnetic distortions.";
UPDATE trial_map SET release_year=2017 WHERE name="Ligneous Megalopolitan";
UPDATE trial_map SET release_year=2023 WHERE name="Gehenna";
UPDATE trial_map SET release_year=2021 WHERE name="Aggregate";
UPDATE trial_map SET release_year=2025 WHERE name="Aggiornamento";
UPDATE trial_map SET release_year=2021 WHERE name="Woolen Calamity";
UPDATE trial_map SET release_year=2015 WHERE name="Uaxactun";
UPDATE trial_map SET release_year=2021 WHERE name="Spirit's glade";
UPDATE trial_map SET release_year=2023 WHERE name="Silversong";
UPDATE trial_map SET release_year=2021 WHERE name="Reign of Kronos";
UPDATE trial_map SET release_year=2016 WHERE name="Rainbow Tylenol 2";
UPDATE trial_map SET release_year=2018 WHERE name="Psychosomatic Exhaustion 2";
UPDATE trial_map SET release_year=2019 WHERE name="PEZ";
UPDATE trial_map SET release_year=2022 WHERE name="octahedral";
UPDATE trial_map SET release_year=2015 WHERE name="Krakatindur";
UPDATE trial_map SET release_year=2020 WHERE name="Feria Sevilla.";
UPDATE trial_map SET release_year=2024 WHERE name="Endless Sunrise";
UPDATE trial_map SET release_year=2020 WHERE name="Empyreum";
UPDATE trial_map SET release_year=2023 WHERE name="Cryptomnesia";
UPDATE trial_map SET release_year=2024 WHERE name="Ashbreaker";
UPDATE trial_map SET release_year=2020 WHERE name="ASEC";
UPDATE trial_map SET release_year=2025 WHERE name="Ancient Myth";
UPDATE trial_map SET release_year=2022 WHERE name="Aggrandizement";
UPDATE trial_map SET release_year=2022 WHERE name="aerial toms";
UPDATE trial_map SET release_year=2024 WHERE name="Super Monkey Ball";
UPDATE trial_map SET release_year=2024 WHERE name="Shadowed Reflections";
UPDATE trial_map SET release_year=2021 WHERE name="Ringworld";
UPDATE trial_map SET release_year=2025 WHERE name="Restriction";
UPDATE trial_map SET release_year=2023 WHERE name="Relikt";
UPDATE trial_map SET release_year=2014 WHERE name="Pipe Torture";
UPDATE trial_map SET release_year=2022 WHERE name="Phantom Realm";
UPDATE trial_map SET release_year=2018 WHERE name="Oriental Reverie";
UPDATE trial_map SET release_year=2021 WHERE name="Oneiros";
UPDATE trial_map SET release_year=2024 WHERE name="Nando Industries";
UPDATE trial_map SET release_year=2023 WHERE name="Lumaria";
UPDATE trial_map SET release_year=2017 WHERE name="Last Chapter";
UPDATE trial_map SET release_year=2025 WHERE name="I.O.N.";
UPDATE trial_map SET release_year=2021 WHERE name="Infernal Gauntlet";
UPDATE trial_map SET release_year=2022 WHERE name="Khepri Ur";
UPDATE trial_map SET release_year=2021 WHERE name="Hidden Palace";
UPDATE trial_map SET release_year=2011 WHERE name="Heaven's on FIRE";
UPDATE trial_map SET release_year=2023 WHERE name="Groundhog Asylum";
UPDATE trial_map SET release_year=2025 WHERE name="Field of currents";
UPDATE trial_map SET release_year=2024 WHERE name="Farewell Quest";
UPDATE trial_map SET release_year=2025 WHERE name="Dune";
UPDATE trial_map SET release_year=2020 WHERE name="Curse of the Ancients";
UPDATE trial_map SET release_year=2013 WHERE name="Crocodile Dundee";
UPDATE trial_map SET release_year=2017 WHERE name="croaking toad";
UPDATE trial_map SET release_year=2011 WHERE name="complexity of road works";
UPDATE trial_map SET release_year=2017 WHERE name="Badlands";
UPDATE trial_map SET release_year=2021 WHERE name="Auburn Estuary";
UPDATE trial_map SET release_year=2023 WHERE name="Ascension to Heaven";
UPDATE trial_map SET release_year=2025 WHERE name="Arcadia";
UPDATE trial_map SET release_year=2022 WHERE name="Abstracture";
UPDATE trial_map SET release_year=2025 WHERE name="Threadbare";
UPDATE trial_map SET release_year=2013 WHERE name="Roofs of Dubai";
UPDATE trial_map SET release_year=2023 WHERE name="Respiration";
UPDATE trial_map SET release_year=2023 WHERE name="Nyxorithal";
UPDATE trial_map SET release_year=2021 WHERE name="Natrialum";
UPDATE trial_map SET release_year=2021 WHERE name="Metavoid";
UPDATE trial_map SET release_year=2024 WHERE name="Metallic Solstice";
UPDATE trial_map SET release_year=2015 WHERE name="Lavender Town";
UPDATE trial_map SET release_year=2018 WHERE name="Hydrogen";
UPDATE trial_map SET release_year=2023 WHERE name="Hidden Curiosity";
UPDATE trial_map SET release_year=2025 WHERE name="Glorpium";
UPDATE trial_map SET release_year=2015 WHERE name="Fury Road";
UPDATE trial_map SET release_year=2018 WHERE name="Eternal Winter";
UPDATE trial_map SET release_year=2022 WHERE name="Elysium";
UPDATE trial_map SET release_year=2018 WHERE name="Cygnus";
UPDATE trial_map SET release_year=2025 WHERE name="Cloudburst.";
UPDATE trial_map SET release_year=2020 WHERE name="Cloud District";
UPDATE trial_map SET release_year=2023 WHERE name="City of Tears";
UPDATE trial_map SET release_year=2024 WHERE name="carbon universe.";
UPDATE trial_map SET release_year=2016 WHERE name="Canopus";
UPDATE trial_map SET release_year=2014 WHERE name="A S T R A L";
UPDATE trial_map SET release_year=2015 WHERE name="Abe's Oddysee";
UPDATE trial_map SET release_year=2024 WHERE name="Erebus";
UPDATE trial_map SET release_year=2024 WHERE name="Dystopia";