export type IconName =
    'x'
    | 'check'
    | 'circle-info'
    | 'chevron-down'
    | 'chevron-up'
    | 'moon'
    | 'sun'
    | 'star-fill'
    | 'discord'
    | 'lock'
    | 'lock-open'
    | 'triangle'
    | 'image'
    | 'house'
    | 'flag'
    | 'focus';
